SELECT YEAR, MONTH, GENDER, COUNT(*) AS USERS
FROM USER_INFO AS A
JOIN (
    SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, USER_ID
    FROM ONLINE_SALE
    GROUP BY YEAR, MONTH, USER_ID
) AS B ON A.USER_ID = B.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER