SELECT MONTH(A.START_DATE) AS MONTH, A.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A, (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '2022-08-01' <= START_DATE AND START_DATE <= '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
) AS T
WHERE A.CAR_ID = T.CAR_ID AND
    '2022-08-01' <= A.START_DATE AND A.START_DATE <= '2022-10-31'
GROUP BY MONTH(A.START_DATE), A.CAR_ID
HAVING RECORDS > 0
ORDER BY MONTH, CAR_ID DESC