SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, CASE
                               WHEN USER_ID = 0 THEN NULL
                               ELSE USER_ID
                               END AS USER_ID
                               , SALES_AMOUNT
FROM (
SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-03'

UNION ALL

SELECT SALES_DATE, PRODUCT_ID, 0 AS USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-03'
) AS A
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID