SELECT CONVERT(DATE_FORMAT(DATETIME, '%H'), SIGNED) AS 'HOUR', COUNT(*) AS 'COUNT'
FROM ANIMAL_OUTS
WHERE DATE_FORMAT(DATETIME, '%H') >= '09' 
    AND DATE_FORMAT(DATETIME, '%H') <= '19'
GROUP BY DATE_FORMAT(DATETIME, '%H')
ORDER BY DATE_FORMAT(DATETIME, '%H')
