SELECT A.CAR_ID, CASE 
                 WHEN B.CAR_ID IS NOT NULL THEN '대여중'
                 ELSE '대여 가능'
                 END AS 'AVAILABILITY'
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A
LEFT OUTER JOIN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE (DATE_FORMAT(START_DATE, '%Y-%m-%d')) <= '2022-10-16' AND
          '2022-10-16' <= (DATE_FORMAT(END_DATE, '%Y-%m-%d'))
) AS B ON A.CAR_ID = B.CAR_ID
GROUP BY A.CAR_ID
ORDER BY A.CAR_ID DESC