SELECT T.FLAVOR
FROM (
    SELECT A.FLAVOR, A.TOTAL_ORDER + B.TOTAL_ORDER AS TOTAL
    FROM FIRST_HALF AS A
    JOIN (
        SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
        FROM JULY
        GROUP BY FLAVOR
    ) AS B ON A.FLAVOR = B.FLAVOR
    GROUP BY A.FLAVOR
    ORDER BY TOTAL DESC LIMIT 3
) AS T