SELECT A.FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAV
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) AS A, REST_INFO AS B
WHERE A.FOOD_TYPE = B.FOOD_TYPE AND FAVORITES = MAX_FAV
ORDER BY FOOD_TYPE DESC
