SELECT C.CAR_ID, C.CAR_TYPE, ROUND(DAILY_FEE * (100-DISCOUNT_RATE) * 0.01 * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C
JOIN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY CAR_ID
    HAVING MIN(DATE_FORMAT(START_DATE, '%Y-%m-%d')) > '2022-11-30' OR
           MAX(DATE_FORMAT(END_DATE, '%Y-%m-%d')) < '2022-11-01'
) AS H ON C.CAR_ID = H.CAR_ID
JOIN (
    SELECT CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
    WHERE DURATION_TYPE = '30일 이상'
) AS P ON C.CAR_TYPE = P.CAR_TYPE
WHERE (C.CAR_TYPE = '세단' OR C.CAR_TYPE = 'SUV')
      AND ROUND(DAILY_FEE * 30 * (100-DISCOUNT_RATE) * 0.01) BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC;